workflows:
  android-builds:
    name: Urban Auto - Signed APK + AAB (Stable)
    max_build_duration: 120

    environment:
      node: 22
      java: 21
      groups:
        - supabase

    android_signing:
      - keystore_reference

    scripts:
      - name: Install dependencies
        script: |
          rm -rf node_modules
          npm install
          npm install @capacitor/assets --save-dev

      - name: Build Next.js
        script: |
          npm run build

      - name: Ensure Android platform exists
        script: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi

      - name: Generate Android icons (adaptive)
        script: |
          npx capacitor-assets generate --android

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build Signed APK + AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
